module.exports={
    devServer:{
        host:'localhost',
        port:9090,
        proxy:{
            'api':{
                target:'http://mall-pre.springboot.cn',
                changeOrigin:true,
                pathRewrite:{
                    "/api":''
                }
            }
        }
    },
    lintOnSave:false
}