module.exports={
    devServer:{
        host:'localhost',
        port:9090,
        proxy:{
            'api':{
                target:'http://mall-pre.springboot.cn',
                changeOrigin:true,
                pathRewrite:{
                    "/api":''
                }
            }
        }
    },
    // publicPath:'/app',
    outputDir:'dist',
    indexPath:'mimall.html',
    lintOnSave:true,
    productionSourceMap:false,
    chainWebpack:config=>{//删除预加载
        config.plugins.delete('prefetch');
    }
}