module.exports={
    devServer:{
        host:'localhost',
        port:9090,
        proxy:{
            'api':{
                target:'http://mall-pre.springboot.cn',
                changeOrigin:true,
                pathRewrite:{
                    "/api":''
                }
            }
        }
    },
    publicPath:'/app',
    outputDir:'dist',
    indexPath:'index2.html',
    lintOnSave:true,
    productionSourceMap:true
}